; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3usbotg]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200


; Specific settings for the first MCU
[env:mcu_1]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = knolleary/PubSubClient
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
; Tell PlatformIO to ignore all files, then ONLY include mcu_beta.cpp
build_src_filter = -<*> +<advertiser.cpp>

; Specific settings for the second MCU
[env:mcu_2]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = knolleary/PubSubClient
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
; Tell PlatformIO to ignore all files, then ONLY include mcu_beta.cpp
build_src_filter = -<*> +<scanner.cpp>
;build_src_filter = -<*> +<scan.cpp> ;testing scanning

; Specific settings for the second MCU
[env:d1]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = knolleary/PubSubClient
monitor_speed = 115200
upload_port = COM3 ; auto detect the COM port for upload   
monitor_port = COM3 ;auto detect the COM port for upload and monitor
; Tell PlatformIO to ignore all files, then ONLY include mcu_beta.cpp
build_src_filter = -<*> +<BLE.cpp> +<AWS_CONFIGS.cpp> +<Main.cpp>
;build_src_filter = -<*> +<scan.cpp> ;testing scanning

; Specific settings for the second MCU
[env:d2]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = knolleary/PubSubClient
monitor_speed = 115200
upload_port = COM4 ; auto detect the COM port for upload   
monitor_port = COM4 ;auto detect the COM port for upload and monitor
; Tell PlatformIO to ignore all files, then ONLY include mcu_beta.cpp
build_src_filter = -<*> +<BLE.cpp> +<AWS_CONFIGS.cpp> +<Main.cpp>
;build_src_filter = -<*> +<scan.cpp> ;testing scanning


